spring.application.name=EventManagement

# Kullanıcı adı ve şifre sormadan, bilgisayar oturumu ile MSSQL'e bağlanma ayarı
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EventManagementSystem;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver