spring.application.name=EventManagement

# Şifreli bağlantı ayarları
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EventsManagementSystem;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Salih.12345
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver