spring.application.name=EventManagement
server.port=8080

# ===== Database Configuration =====
# Şifreli bağlantı ayarları
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EventsManagementSystem;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Salih.12345
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===== JPA / Hibernate Configuration =====
spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ===== Logging Configuration =====
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===== Jackson Configuration =====
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC+3

# ===== Error Handling =====
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false